name: "Tests"

on: [push]

jobs:
  build:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
      env:
        BT_ENVIRONMENT: ${{ secrets.BT_ENVIRONMENT }}
        BT_MERCHANT_ID: ${{ secrets.BT_MERCHANT_ID }}
        BT_PUBLIC_KEY: ${{ secrets.BT_PUBLIC_KEY }}
        BT_PRIVATE_KEY: ${{ secrets.BT_PRIVATE_KEY }}
    - run: npm install
    - run: npm run test:unit
    - run: npm start & sleep 3 && npm run test:integration
